### ISSUE TITLE
test/document Photon WiFi access protocol

### ISSUE THREAD

**Issue by loopstick** [Berkeley-MDes/desinv-202#3]
document the steps necessary to connect a Particle device to UC Berkeley WiFi
post on gitHub Wiki

**Comment by loopstick** [comment]
https://github.com/Berkeley-MDes/desinv-202/wiki/Connect-Photon-to-Cal-WiFi-%E2%80%90-How-To#method-1-worked-1-of-1-times-

**Comment by loopstick** [comment]
@equilet please test this and give feedback
https://github.com/Berkeley-MDes/desinv-202/wiki/Connect-Photon-to-Cal-WiFi-%E2%80%90-How-To#method-1-worked-1-of-1-times-

**Comment by equilet** [comment]
Will do.  

I think it will be useful to enumerate all of the options somewhere, but I want to have a distinct area (possibly this exact page) where we document a more "all-inclusive", singular approach.  Having so many options seems complicated with the associated support required in class.  

_(documenting some history...)_

I suppose my goal here is to figure out a foolproof way to get people up and running out of the box, and also while in 310.  Sure, it'd be nice to have them grab the MAC address first, but I don't think we can rely on that.  I'll be going on campus tomorrow morning to check this out in detail w/ the photon2.

`eduroam` is an enterprise network that requires a WPA2 pwd.  This is what I used on-site to set username/pwd details for the photon2 in order to get the MAC address, which in turn allowed me to switch over to the IoT network by adding the device in UCB's portal interface.  My experience was that it took ~5-10 tries in order to take.  This was with the photon1 and I'm hoping it is smoother with the p2.  One of the issues was that different networks with the same name keep popping up in the terminal.  I'll try it in VS code next, so as to aim at the singular approach.  I'm most interested in documenting 
1. how to fill a particular wifi slot (out of 5)
2. how to post all slot info so that it's easy for the students to track on their photon2

**Comment by loopstick** [comment]
sure, the idea of this page for now is that it's a place for us to track what has been tired (feel free to post the methods you've tested).

When we release this to students we'll only release the 1 method to rule them all: whichever method proves to be the most robust.

**Comment by tj60647** [comment]
Have either of you tried particle serial wifi in the CLI [particle workbench]?  
https://docs.particle.io/reference/developer-tools/cli/#particle-serial-wifi

"You will need to use this command to set up a device using WPA2 Enterprise and services like EduRoam that use it."

**Comment by tj60647** [comment]
connect the photon 2 device via usb. Launch the CLI from the particle workbench home page. type: particle serial wifi

![image](https://github.com/Berkeley-MDes/desinv-202/assets/1688450/d13ad34c-fb76-484e-aa1c-cda7f95247ae)

**Comment by equilet** [comment]
yes this is my preferred flow – and precisely what I'm testing tomorrow – but we still don't know if it will be any smoother than what I ran into last week

**Comment by loopstick** [comment]
not yet, just got VSCode installed and added Particle Workbench extension.

I could not get Particle Workbench to install as a standalone app (as the Particle website seems to suggest).

**Comment by tj60647** [comment]
Also you can use Putty or whatever to connect to the device via serial port and then just type 'm'. Here I am using the serial interface in VSCode:
![image](https://github.com/Berkeley-MDes/desinv-202/assets/1688450/d0c0cad9-529c-4b67-bb4a-4078e707ff0f)

**Comment by tj60647** [comment]
The device needs to be in 'listening mode', which is flashing blue.

**Comment by loopstick** [comment]
add a method in the doc and write it up!

**Comment by equilet** [comment]
just added

**Comment by loopstick** [comment]
saw it.

I did a little rearranging. 
there are two processes on this page (maybe they should be separated into individual pages)

1. Connecting to Cal Wifi
2. Find MAC Address (in order to register device and connect to Berkeley-IoT)

if your eduroam login method works, there's no need to find MAC addresses, register with Berkeley-IoT, etc

**Comment by equilet** [comment]
I would highly prefer to get them onto the IoT network.  It's what it's designed for, and AFAIK campus prefers that devices like this be registered/tracked individually.  We can discuss tomorrow.

**Comment by loopstick** [comment]
exactly, no need to discuss. I would also prefer to use the IoT network. 
That's why we're documenting how to get a MAC address...

**Comment by equilet** [comment]
good news shared by TJ today - I think his method (which is basically what we'd thought would be the 'best practice' that covers all platforms) seems to be working nicely

**Comment by LoopstickCal** [comment]
typo in step 7 -> "yes" not "yet" 
step 8 -> "enter password"  (the password generated in step 7 above)

**Comment by equilet** [comment]
updated

**Comment by equilet** [comment]
I'm going to forego the suggestion to use this type of numbering - you'll note that I'm using auto-generated IDs for the numbers so that I don't have to actually type in steps manually https://linuxhint.com/markdown-numbered-lists/

**Comment by equilet** [comment]
I am ready to close this issue.  Before I do this I would like to have both TJ and Sudhu test the process with their devices within the next couple of weeks on campus.  Is this a reasonable ask?

**Comment by LoopstickCal** [comment]
yes. Open new "test"  issues for each of us?

change this issue to "documentation"

**Comment by equilet** [comment]
let's just keep things germaine to the original threads for now.  We can use this one, I assign you two for the issue, and you close when satisfied, or comment again if I need to update something.

**Comment by loopstick** [comment]
This works: [https://github.com/Berkeley-MDes/desinv-202/wiki/Particle:-connecting-a-Photon-2-to-the-UCB-IoT-network](https://github.com/Berkeley-MDes/desinv-202/wiki/Particle:-connecting-a-Photon-2-to-the-UCB-IoT-network)

but I prefer the web API for entering new WiFi credentials: https://docs.particle.io/tools/developer-tools/configure-wi-fi/

I thought I had something written up in the workspace, but looks like it's not there anymore...
